version: 0.2

env:
  variables:
    AWS_ACCOUNT_ID: "969690358446"
  # parameter-store:
  #   key: "value"
  #   key: "value"
  # secrets-manager:
  #   key: secret-id:json-key:version-stage:version-id
  # git-credential-helper: no | yes

phases:
  pre_build:
    commands:
      - echo "Terraform Plan"
      - terraform init
      - terraform plan
      - echo "Ran TF Plan"
      - echo "try aga"
